#!/bin/bash

curl http://bing.com$(curl -s http://www.bing.com/HPImageArchive.aspx\?format\=js\&idx\=0\&n\=1 | jq -r '.images[0].url') >~/.config/hypr/desktop.jpg

hyprctl hyprpaper preload "~/.config/hypr/desktop.jpg"
hyprctl hyprpaper wallpaper ", ~/.config/hypr/desktop.jpg"

cp ~/.config/hypr/desktop.jpg /usr/share/sddm/themes/catppuccin-macchiato/backgrounds/wall.jpg
