return {
  {
    "nvim-treesitter/nvim-treesitter",
    -- branch = "main",
    -- dir = "C:\\repos\\github\\gpetrites\\nvim-treesitter",
    -- init = function() end,
    opts = {
      ensure_installed = {
        "c_sharp",
        "html",
        "javascript",
        "jsdoc",
        "json",
        "jsonc",
        "lua",
        "luadoc",
        "luap",
        "markdown",
        "markdown_inline",
        "python",
        "toml",
        "tsx",
        "typescript",
        "xml",
        "yaml",
      },
    }, -- config = function() end,
  },
  -- {
  --   "nvim-teesitter/nvim-treesitter-textobjects",
  --   branch = "main",
  --   -- dir = "C:\\repos\\github\\gpetrites\\nvim-treesitter",
  --   config = function() end,
  -- },
}
